# .travis.yml for R projects.
#
# https://travis-ci.org/flr/FLCore

warnings_are_errors: false

language: r

matrix:
  include:
    - os: linux
      r: release

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
